add_cus_dep('md', 'mdtex', 0, 'md2tex');
sub md2tex {
  return system("
    cat $_[0].md | sed -r '
    s/@@/@@ /g
    s/##/## /g
    s/@([A-Za-z0-9-]+)/\\\\cite{\\1}/g
    s/#([A-Za-z0-9-]+)/\\\\autoref{\\1}/g
    s/@@ /@/g
    s/## /#/g
    ' | pandoc --listings -f markdown -t latex -o $_[0].mdtex");
};
